### PR TITLE
Disable Theme Cache by default.

### LINKED ISSUE #10: Apply cache settings when no manual config supplied.
Although you can supply a standalone.xml via `keycloak/configuration`, theme and template cache is active by default. This makes it so that if you do not supply a full config, live updating does not work.

We need a solution to change these cache settings in the kit so that it is always off by default.

### PR DESCRIPTION
**Pull request by tmtek**
Added a script that is added as a volume that disables the Keycloak theme cache.

### CODE REVIEW

File: scripts/docker-build.js [hunk 1]
```diff
@@ -31,15 +32,31 @@ function populateArg(path) {
...
-	const themes = packageJs.keycloak.themes.map(({dir, name}) => `      - "${dir}:/opt/jboss/keycloak/themes/${name}"`);
+function populateVolumes() {
+	const themes = getThemes();
+	const scripts = getScripts()//;
+	const volumes = [...themes, ...scripts];
 	replace.sync({
 		files:`./docker-compose.yml`,
 		from:`%volumes%`,
-		to:themes.length > 0 ? 'volumes:\n' + themes.join('\n') : ''
+		to:themes.length > 0 ? 'volumes:\n' + volumes.join('\n') : ''
```
Comment (tmtek) [inline scripts/docker-build.js]: have to check volume length not theme length here.

File: scripts/docker-build.js [hunk 2]
```diff
@@ -31,15 +32,31 @@ function populateArg(path) {
 	});
 }
 
-function populateThemes() {
-	const themes = packageJs.keycloak.themes.map(({dir, name}) => `      - "${dir}:/opt/jboss/keycloak/themes/${name}"`);
+function populateVolumes() {
+	const themes = getThemes();
+	const scripts = getScripts()//;
```
Comment (tmtek) [inline scripts/docker-build.js]: Ditch the comments here.
